### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by r4v3n6101** [Gekkio/imgui-rs#150] opened 2018-08-30 10:31 UTC
Running of hello_world demo crashes program with following output: 

> thread '<unnamed>' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', ...\winit-0.16.2\src\dpi.rs:153:9

**Comment by malikolivier** [comment] 2018-09-09 03:52
Could you let us know your OS and environment so that someone can try to reproduce this bug?

**Comment by r4v3n6101** [comment] 2018-09-09 18:52
OS: Windows 7 x86
Rust:1.28.0-msvc
Running with --release

**Comment by Gekkio** [comment] 2018-09-09 19:51
This looks like winit bug 607: https://github.com/tomaka/winit/issues/607

It's been fixed in winit 0.17, but the problem is glium still ends up using winit 0.16 through this dependency chain:

imgui-glium-renderer -> glium 0.22 -> glutin 0.17 -> winit 0.16

I don't think we can do anything to fix this at the moment, but once glium is updated with glutin 0.18, we can in turn update glium.

**Closed** 2018-12-04 22:55 UTC
