### ISSUE TITLE
Use imgui with PistonWindow

### ISSUE THREAD

**Issue by dvdplm** [Gekkio/imgui-rs#87] opened 2017-11-10 21:33 UTC
I was trying to make imgui work with a PistonWindow and ran into an issue I understand too poorly to fix.

I create my window like this:
```rust
  let window: PistonWindow = WindowSettings::new("piston: image", [w, h])
    .exit_on_esc(true)
    .opengl(opengl)
    .build()
    .unwrap();
```

and then later in the code I try to initialise a `mgui_gfx_renderer::Renderer` for imgui with this:

```rust
let mut renderer = Renderer::init(&mut imgui, &mut window.factory, shaders, window.output_color).unwrap();
```

I get this error:

```
expected type `gfx_core::handle::RenderTargetView<_, (gfx_core::format::R8_G8_B8_A8, gfx_core::format::Unorm)>`
              found type `gfx_core::handle::RenderTargetView<_, (gfx_core::format::R8_G8_B8_A8, gfx_core::format::Srgb)>`
```

I have tried to figure out why the two libraries use different colour formats but I am simply not knowledgeable enough. Can anyone help?

Is there a better, canonical way of building a imgui UI with Piston?

**Comment by Gekkio** [comment] 2017-11-11 08:50
Yeah, this happens because `Renderer` and `PistonWindow` disagree about the output format. `Renderer` doesn't really care that much about this fine detail, but when I wrote the code I couldn't figure out how to parameterize it so that it could work with both (the problem is the use of the gfx_pipeline! macro). Sorry 😢 

At this point your best bet is probably to fork imgui-rs on github and depend on the fork instead. All you need to do is change all instances (4 if I counted right) of `gfx::format::Rgba8` to `gfx::format::Srgba8` in `imgui-gfx-renderer/src/lib.rs` and it should be compatible with `PistonWindow`. The fix is simple but unfortunately I can't do this in the actual library right now because that would break existing code depending on `Rgba8` format.

If I figure out how to support both color formats (probably by unrolling the macro by hand), I'll try to fix this issue. Piston is a significant library in the Rust gamedev ecosystem and supporting it is definitely a priority. Thanks for reporting this!

**Comment by dvdplm** [comment] 2017-11-11 14:25
> change all instances (4 if I counted right) of gfx::format::Rgba8 to gfx::format::Srgba8

Yes, this works and will let me keep working on my little experiment. Thanks! :)

**Comment by Gekkio** [comment] 2019-07-01 21:20
Closing since both color formats are supported since `0.1.0-rc.1`

**Closed by Gekkio** 2019-07-01 21:20 UTC
